sudo: false
language: node_js
node_js:
  - "stable"


  #npm ci
install:
  npm ci
  npm install --save-dev jest

cache:
  directories:
    - "node_modules"



#npm test


  env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8