sudo: false
language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

#install:
#  npm ci

#npm test


  env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8