sudo: false
language: node_js
node_js:
  - "stable"


install:
  npm ci
  npm i --save-dev mocha  #Proper installation of Mocha to make it a Dependency?
  npm i --save-dev chai  #Installation to make Chai a dependency?
  # npm install --save-dev jest
  #Mocha will be accessable by : ./node_modules/mocha/bin/mocha
  #npm test
  

cache:
  directories:
    - "node_modules"






  env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8