export const SOME_CASE = 'SOME_CASE'
export const HYDRATE_MEDICATION = 'HYDRATE_MEDICATION'
export const HYDRATE_PATIENT = 'HYDRATE_PATIENT'
export const CLEAR_MEDICATION = 'CLEAR_MEDICATION'
export const HYDRATE_MED_ARRAY = 'HYDRATE_MED_ARRAY';

